//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1094.0 using the following command:
// xscgen -v -n WOT.TAK.Connection.DTOs TAKconn-DotNet\WOT.TAK.Connection\Protocol\Xml\Wot\**\*.xsd -o TAKconn-DotNet\WOT.TAK.Connection\Protocol\Xml\DTOs
namespace WOT.TAK.Connection.DTOs
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("auth", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("auth", Namespace="")]
    public partial class Auth
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("cot")]
        public AuthCot Cot { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AuthCot", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthCot
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("username")]
        public string Username { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("password")]
        public string Password { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("uid")]
        public string Uid { get; set; }
    }

    /// <summary>
    /// <para>This is a Cursor On Target detail sub-schema that holds "fingerprints" of the system that have processed
    ///                a particular CoT event. This information aids in the routine of CoT messages along a particular
    ///                processing chain. Each system that touches a particular CoT event is expected to add its own attribute
    ///                to this entity. The attribute name should reflect the particular system name, and the value should be
    ///                the time stamp when the information was sent out from that system. Some illustrative _flow-tags_
    ///                attributes are adocs, fbcb2, and tadilj, but the attribute list is not a closed set.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"This is a Cursor On Target detail sub-schema that holds ""fingerprints"" of the system that have processed a particular CoT event. This information aids in the routine of CoT messages along a particular processing chain. Each system that touches a particular CoT event is expected to add its own attribute to this entity. The attribute name should reflect the particular system name, and the value should be the time stamp when the information was sent out from that system. Some illustrative _flow-tags_ attributes are adocs, fbcb2, and tadilj, but the attribute list is not a closed set.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("_flow-tags_", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FlowTags
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.XmlElement> _any;

        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="FlowTags" /> class.</para>
        /// </summary>
        public FlowTags()
        {
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.XmlElement>();
            this._anyAttribute = new System.Collections.ObjectModel.Collection<System.Xml.XmlAttribute>();
        }

        [System.Xml.Serialization.XmlAttributeAttribute("version")]
        public decimal Version { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Version property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VersionSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.XmlAttribute> _anyAttribute;

        /// <summary>
        /// <para>A system-specific flowtag identifier associated with the encapsulating CoT object.
        ///                    The attribute value should be a xs:dateTime value.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A system-specific flowtag identifier associated with the encapsulating CoT object" +
            ". The attribute value should be a xs:dateTime value.")]
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
    }

    /// <summary>
    /// <para>An optional element used to hold CoT sub-schema. empty element</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("An optional element used to hold CoT sub-schema. empty element")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("detail", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Detail
    {

        [System.Xml.Serialization.XmlElementAttribute("TakControl")]
        public TakControl TakControl { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("m_color")]
        public string MColor { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("m_contact")]
        public string MContact { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("m_link")]
        public string MLink { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("m_remarks")]
        public string MRemarks { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("m_status")]
        public string MStatus { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("m_takv")]
        public string MTakv { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("m_track")]
        public string MTrack { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("m_usericon")]
        public string MUsericon { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("__chat")]
        public Chat Chat { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("__group")]
        public Group Group { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("__serverdestination")]
        public Serverdestination Serverdestination { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("_medevac_")]
        public Medevac Medevac { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("color")]
        public Color Color { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("contact")]
        public Contact Contact { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("emergency")]
        public Emergency Emergency { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("link")]
        public Link Link { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Marti")]
        public Marti Marti { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Precisionlocation")]
        public Precisionlocation Precisionlocation { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("remarks")]
        public Remarks Remarks { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("status")]
        public Status Status { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("takv")]
        public Takv Takv { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("track")]
        public Track Track { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("usericon")]
        public Usericon Usericon { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("uid")]
        public Uid Uid { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("_flow-tags_")]
        public WOT.TAK.Connection.DTOs.FlowTags FlowTags { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TakControl", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TakControl
    {

        [System.Xml.Serialization.XmlElementAttribute("TakProtocolSupport")]
        public TakProtocolSupport TakProtocolSupport { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TakServerVersionInfo")]
        public TakServerVersionInfo TakServerVersionInfo { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TakRequest")]
        public TakRequest TakRequest { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TakResponse")]
        public TakResponse TakResponse { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TakProtocolSupport", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TakProtocolSupport
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _version = "1";

        [System.ComponentModel.DefaultValueAttribute("1")]
        [System.Xml.Serialization.XmlAttributeAttribute("version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TakServerVersionInfo", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TakServerVersionInfo
    {

        [System.Xml.Serialization.XmlAttributeAttribute("apiVersion")]
        public string ApiVersion { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("serverVersion")]
        public string ServerVersion { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TakRequest", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TakRequest
    {

        [System.Xml.Serialization.XmlAttributeAttribute("version")]
        public string Version { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TakResponse", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TakResponse
    {

        [System.Xml.Serialization.XmlAttributeAttribute("status")]
        public bool Status { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Status property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("__chat", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Chat
    {

        [System.Xml.Serialization.XmlElementAttribute("chatgrp")]
        public Chatgrp Chatgrp { get; set; }

        /// <summary>
        /// <para>TBD: the callsign of the receiver?</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("TBD: the callsign of the receiver?")]
        [System.Xml.Serialization.XmlAttributeAttribute("chatroom")]
        public string Chatroom { get; set; }

        /// <summary>
        /// <para>TBD,</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("TBD,")]
        [System.Xml.Serialization.XmlAttributeAttribute("groupOwner")]
        public bool GroupOwner { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the GroupOwner property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroupOwnerSpecified { get; set; }

        /// <summary>
        /// <para>TBD: the unique ID of the sender?</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("TBD: the unique ID of the sender?")]
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("parent")]
        public string Parent { get; set; }

        /// <summary>
        /// <para>the call sign of the sender</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("the call sign of the sender")]
        [System.Xml.Serialization.XmlAttributeAttribute("senderCallsign")]
        public string SenderCallsign { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("messageId")]
        public string MessageId { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("deleteChild")]
        public string DeleteChild { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("chatgrp", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Chatgrp
    {

        /// <summary>
        /// <para>third ID</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("third ID")]
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }

        /// <summary>
        /// <para>the machine ID of the sender</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("the machine ID of the sender")]
        [System.Xml.Serialization.XmlAttributeAttribute("uid0")]
        public string Uid0 { get; set; }

        /// <summary>
        /// <para>another ID</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("another ID")]
        [System.Xml.Serialization.XmlAttributeAttribute("uid1")]
        public string Uid1 { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("__group", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Group
    {

        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("role")]
        public string Role { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("__serverdestination", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Serverdestination
    {

        /// <summary>
        /// <para>string composed by IP:port: protocol:machineID. e.g.
        ///                        192.168.0.103:4242:tcp:ANDROID-R52JB0CDC4E</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("string composed by IP:port: protocol:machineID. e.g. 192.168.0.103:4242:tcp:ANDRO" +
            "ID-R52JB0CDC4E")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("destinations")]
        public string Destinations { get; set; }
    }

    /// <summary>
    /// <para>the medevac class is used to describe a case of someone in need to be evacuated</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("the medevac class is used to describe a case of someone in need to be evacuated")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("_medevac_", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Medevac
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("casevac")]
        public string Casevac { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("equipment_none")]
        public string EquipmentNone { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("freq")]
        public string Freq { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("hlz_marking")]
        public string HlzMarking { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("litter")]
        public string Litter { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("medline_remarks")]
        public string MedlineRemarks { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Priority")]
        public string Priority { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("routine")]
        public string Routine { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Security")]
        public string Security { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("terrain_none")]
        public string TerrainNone { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Title")]
        public string Title { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("urgent")]
        public string Urgent { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("zone_prot_selection")]
        public string ZoneProtSelection { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("color", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Color
    {

        [System.Xml.Serialization.XmlAttributeAttribute("argb")]
        public string Argb { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("contact", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Contact
    {

        [System.Xml.Serialization.XmlAttributeAttribute("callsign")]
        public string Callsign { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("endpoint")]
        public string Endpoint { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("iconsetpath")]
        public string Iconsetpath { get; set; }
    }

    /// <summary>
    /// <para>An emergency beacon the is continually send to all the connected clients until deactivated
    ///                from the original creator</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("An emergency beacon the is continually send to all the connected clients until de" +
        "activated from the original creator")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("emergency", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Emergency
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Alert")]
        public string Alert { get; set; }

        /// <summary>
        /// <para>if true the emergency beacon is canceled</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("if true the emergency beacon is canceled")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("cancel")]
        public string Cancel { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("type")]
        public string Type { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("link", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Link
    {

        [System.Xml.Serialization.XmlAttributeAttribute("parent_callsign")]
        public string ParentCallsign { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("production_time", DataType="dateTime")]
        public System.DateTime ProductionTime { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ProductionTime property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductionTimeSpecified { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("relation")]
        public string Relation { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("uid")]
        public string Uid { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Marti", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Marti
    {

        [System.Xml.Serialization.XmlElementAttribute("dest")]
        public Dest Dest { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("dest", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Dest
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("callsign")]
        public string Callsign { get; set; }
    }

    /// <summary>
    /// <para>some type of location?</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("some type of location?")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Precisionlocation", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Precisionlocation
    {

        /// <summary>
        /// <para>TDB can be DTED0 or ???</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("TDB can be DTED0 or ???")]
        [System.Xml.Serialization.XmlAttributeAttribute("altsrc")]
        public string Altsrc { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("geopointsrc")]
        public string Geopointsrc { get; set; }
    }

    /// <summary>
    /// <para>Provides a place to annotate CoT with free text information. e.g. comments from other
    ///                users about the current COT. Used also from the geoChat.</para>
    /// <para>the xml body of this class is used to transport the chat message</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Provides a place to annotate CoT with free text information. e.g. comments from o" +
        "ther users about the current COT. Used also from the geoChat. the xml body of th" +
        "is class is used to transport the chat message")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("remarks", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Remarks
    {

        [System.Xml.Serialization.XmlAttributeAttribute("source")]
        public string Source { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("sourceID")]
        public string SourceId { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("time", DataType="dateTime")]
        public System.DateTime Time { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Time property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("to")]
        public string To { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("keywords")]
        public string Keywords { get; set; }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("status", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Status
    {

        /// <summary>
        /// <para>% of the battery on the phone</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("% of the battery on the phone")]
        [System.Xml.Serialization.XmlAttributeAttribute("battery")]
        public string Battery { get; set; }

        /// <summary>
        /// <para>probably boolean to determine if ready or not</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("probably boolean to determine if ready or not")]
        [System.Xml.Serialization.XmlAttributeAttribute("readiness")]
        public bool Readiness { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Readiness property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReadinessSpecified { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("takv", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Takv
    {

        /// <summary>
        /// <para>type of physical device</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("type of physical device")]
        [System.Xml.Serialization.XmlAttributeAttribute("device")]
        public string Device { get; set; }

        /// <summary>
        /// <para>the operating system running TAK</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("the operating system running TAK")]
        [System.Xml.Serialization.XmlAttributeAttribute("os")]
        public string Os { get; set; }

        /// <summary>
        /// <para>the variant of TAK</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("the variant of TAK")]
        [System.Xml.Serialization.XmlAttributeAttribute("platform")]
        public string Platform { get; set; }

        /// <summary>
        /// <para>the version of TAK running on the device</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("the version of TAK running on the device")]
        [System.Xml.Serialization.XmlAttributeAttribute("version")]
        public string Version { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("track", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Track
    {

        [System.Xml.Serialization.XmlAttributeAttribute("course")]
        public decimal Course { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Course property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CourseSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("speed")]
        public decimal Speed { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Speed property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SpeedSpecified { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("usericon", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Usericon
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("iconsetpath")]
        public string Iconsetpath { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("uid", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Uid
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Droid")]
        public string Droid { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("nett")]
        public string Nett { get; set; }
    }

    /// <summary>
    /// <para>class COTPOINT</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("class COTPOINT")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("point", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Point
    {

        /// <summary>
        /// <para>Circular 1-sigma or decimal a circular area about the point in meters</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Circular 1-sigma or decimal a circular area about the point in meters")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ce")]
        public decimal Ce { get; set; }

        /// <summary>
        /// <para>Latitude referred to the WGS 84 ellipsoid in degrees</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Latitude referred to the WGS 84 ellipsoid in degrees")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("lat")]
        public decimal Lat { get; set; }

        /// <summary>
        /// <para>Linear 1-sigma error or an altitude range about the point in meters</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Linear 1-sigma error or an altitude range about the point in meters")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("le")]
        public decimal Le { get; set; }

        /// <summary>
        /// <para>Longitude referred to the WGS 84 in degrees</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Longitude referred to the WGS 84 in degrees")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("lon")]
        public decimal Lon { get; set; }

        /// <summary>
        /// <para>HAE acronym for Height above Ellipsoid based on WGS-84 ellipsoid (measured in meters).
        ///                    If absent, the value of the point/@hae in the CoT event base schema is used</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("HAE acronym for Height above Ellipsoid based on WGS-84 ellipsoid (measured in met" +
            "ers). If absent, the value of the point/@hae in the CoT event base schema is use" +
            "d")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("hae")]
        public decimal Hae { get; set; }
    }

    /// <summary>
    /// <para>represents a TAK event: this class is instantiated with a standard set of values.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("represents a TAK event: this class is instantiated with a standard set of values." +
        "")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("event", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("event", Namespace="")]
    public partial class Event
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("point", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Point Point { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("detail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WOT.TAK.Connection.DTOs.Detail Detail { get; set; }

        /// <summary>
        /// <para>Gives a hint about how the coordinates were generated</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Gives a hint about how the coordinates were generated")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("how")]
        public string How { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("m_detail")]
        public string MDetail { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("m_point")]
        public string MPoint { get; set; }

        /// <summary>
        /// <para>ending time when an event should no longer be considered valid</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ending time when an event should no longer be considered valid")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("stale", DataType="dateTime")]
        public System.DateTime Stale { get; set; }

        /// <summary>
        /// <para>starting time when an event should be considered valid</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("starting time when an event should be considered valid")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("start", DataType="dateTime")]
        public System.DateTime Start { get; set; }

        /// <summary>
        /// <para>time stamp: when the event was generated</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("time stamp: when the event was generated")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("time", DataType="dateTime")]
        public System.DateTime Time { get; set; }

        /// <summary>
        /// <para>&lt;font color="#008000"&gt; # Hierarchically organized hint about event type
        ///                        (default is 'a-f-G-I' for infrastructure)&lt;/font&gt;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("&lt;font color=\"#008000\"&gt; # Hierarchically organized hint about event type (de" +
            "fault is \'a-f-G-I\' for infrastructure)&lt;/font&gt;")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type { get; set; }

        /// <summary>
        /// <para>Globally unique name for this information on this event.</para>
        /// <para>can have additional information attached.</para>
        /// <para>e.g. -ping means that this request is a ping</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Globally unique name for this information on this event. can have additional info" +
            "rmation attached. e.g. -ping means that this request is a ping")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("uid")]
        public string Uid { get; set; }

        /// <summary>
        /// <para>Schema version of this event instance (e.g. 2.0)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Schema version of this event instance (e.g. 2.0)")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("version")]
        public decimal Version { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("access")]
        public string Access { get; set; }
    }
}
